# Data Standardization & Variable Transformation

## Standardization

In [36]:
import numpy as np
import pandas as pd

V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame(
        {"V1" : V1,
         "V2" : V2,
         "V3" : V3}        
)



df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [37]:
from sklearn import preprocessing

In [38]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

this is a standardizetion with mean=0, std dev=1

## Normalization

transforming values of a variable into between 0-1; a kind of standardization

In [39]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min-Max Transformation

transforming values of a variable into between any 2 numbers

In [40]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20))

In [41]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

## Binarize Transformation

belirli bir eşik değerin altında veya üstündekileri 0 veya 1e dönüştürür; not standardization but transformation

In [42]:
binarizer = preprocessing.Binarizer(threshold = 5).fit(df)

In [43]:
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

## 0-1 Transformation

transforming categorical variables into numeric variables 0 and 1

In [44]:
import seaborn as sns
tips = sns.load_dataset('tips')
df = tips.copy()
df_l = df.copy()

In [45]:
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [46]:
df_l["new_sex"] = df_l["sex"].cat.codes

In [47]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1
1       10.34  1.66    Male     No  Sun  Dinner     3        0
2       21.01  3.50    Male     No  Sun  Dinner     3        0
3       23.68  3.31    Male     No  Sun  Dinner     2        0
4       24.59  3.61  Female     No  Sun  Dinner     4        1

In [48]:
lbe = preprocessing.LabelEncoder()

In [49]:
df_l["newer_sex"] = lbe.fit_transform(df_l["sex"])

In [50]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  newer_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1          0
1       10.34  1.66    Male     No  Sun  Dinner     3        0          1
2       21.01  3.50    Male     No  Sun  Dinner     3        0          1
3       23.68  3.31    Male     No  Sun  Dinner     2        0          1
4       24.59  3.61  Female     No  Sun  Dinner     4        1          0

## "1 and Others (0)" Transformation

transforming classes of categorical variable with more than 2 classes into "1" and "others"

In [51]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [52]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  new_sex  newer_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        1          0
1       10.34  1.66    Male     No  Sun  Dinner     3        0          1
2       21.01  3.50    Male     No  Sun  Dinner     3        0          1
3       23.68  3.31    Male     No  Sun  Dinner     2        0          1
4       24.59  3.61  Female     No  Sun  Dinner     4        1          0

In [53]:
df_l["new_day"] = np.where(df_l["day"].str.contains("Sun"),1,0)

In [54]:
df_l.head(20)

total_bill   tip     sex smoker  day    time  size  new_sex  newer_sex  \
0        16.99  1.01  Female     No  Sun  Dinner     2        1          0   
1        10.34  1.66    Male     No  Sun  Dinner     3        0          1   
2        21.01  3.50    Male     No  Sun  Dinner     3        0          1   
3        23.68  3.31    Male     No  Sun  Dinner     2        0          1   
4        24.59  3.61  Female     No  Sun  Dinner     4        1          0   
5        25.29  4.71    Male     No  Sun  Dinner     4        0          1   
6         8.77  2.00    Male     No  Sun  Dinner     2        0          1   
7        26.88  3.12    Male     No  Sun  Dinner     4        0          1   
8        15.04  1.96    Male     No  Sun  Dinner     2        0          1   
9        14.78  3.23    Male     No  Sun  Dinner     2        0          1   
10       10.27  1.71    Male     No  Sun  Dinner     2        0          1   
11       35.26  5.00  Female     No  Sun  Dinner     4        1          0   
12       15.42  1.57    Male     No  Sun  Dinner     2        0          1   
13       18.43  3.00    Male     No  Sun  Dinner     4        0          1   
14       14.83  3.02  Female     No  Sun  Dinner     2        1          0   
15       21.58  3.92    Male     No  Sun  Dinner     2        0          1   
16       10.33  1.67  Female     No  Sun  Dinner     3        1          0   
17       16.29  3.71    Male     No  Sun  Dinner     3        0          1   
18       16.97  3.50  Female     No  Sun  Dinner     3        1          0   
19       20.65  3.35    Male     No  Sat  Dinner     3        0          1   

    new_day  
0         1  
1         1  
2         1  
3         1  
4         1  
5         1  
6         1  
7         1  
8         1  
9         1  
10        1  
11        1  
12        1  
13        1  
14        1  
15        1  
16        1  
17        1  
18        1  
19        0

## Multiple Class Transformation

In [55]:
lbe = preprocessing.LabelEncoder()

In [56]:
df_l["newer_day"] = lbe.fit_transform(df_l["day"])

In [57]:
df_l

total_bill   tip     sex smoker   day    time  size  new_sex  newer_sex  \
0         16.99  1.01  Female     No   Sun  Dinner     2        1          0   
1         10.34  1.66    Male     No   Sun  Dinner     3        0          1   
2         21.01  3.50    Male     No   Sun  Dinner     3        0          1   
3         23.68  3.31    Male     No   Sun  Dinner     2        0          1   
4         24.59  3.61  Female     No   Sun  Dinner     4        1          0   
..          ...   ...     ...    ...   ...     ...   ...      ...        ...   
239       29.03  5.92    Male     No   Sat  Dinner     3        0          1   
240       27.18  2.00  Female    Yes   Sat  Dinner     2        1          0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2        0          1   
242       17.82  1.75    Male     No   Sat  Dinner     2        0          1   
243       18.78  3.00  Female     No  Thur  Dinner     2        1          0   

     new_day  newer_day  
0          1          2  
1          1          2  
2          1          2  
3          1          2  
4          1          2  
..       ...        ...  
239        0          1  
240        0          1  
241        0          1  
242        0          1  
243        0          3  

[244 rows x 11 columns]

## One-Hot Transformation and Dummy Variable Trap

In [58]:
df_one_hot = df.copy()

In [59]:
pd.get_dummies(df_one_hot, columns = ["sex"], prefix = ["sex"]).head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

In [60]:
pd.get_dummies(df_one_hot, columns = ["day"], prefix = ["day"]).head()

total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  day_Sat  \
0       16.99  1.01  Female     No  Dinner     2         0        0        0   
1       10.34  1.66    Male     No  Dinner     3         0        0        0   
2       21.01  3.50    Male     No  Dinner     3         0        0        0   
3       23.68  3.31    Male     No  Dinner     2         0        0        0   
4       24.59  3.61  Female     No  Dinner     4         0        0        0   

   day_Sun  
0        1  
1        1  
2        1  
3        1  
4        1

## Transforming Continuous Variable into Categorical Variable

In [61]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [62]:
dff = df.select_dtypes(include = ["float64", "int64"])

In [63]:
est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2], encode = "ordinal", strategy = "quantile").fit(dff)

In [64]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

## Transforming Variable into Index and Index into Variable

In [65]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [66]:
df["new_var"]  = df.index

In [67]:
df["new_var"] = df["new_var"] + 10

In [68]:
df.head()

total_bill   tip     sex smoker  day    time  size  new_var
0       16.99  1.01  Female     No  Sun  Dinner     2       10
1       10.34  1.66    Male     No  Sun  Dinner     3       11
2       21.01  3.50    Male     No  Sun  Dinner     3       12
3       23.68  3.31    Male     No  Sun  Dinner     2       13
4       24.59  3.61  Female     No  Sun  Dinner     4       14

In [69]:
df.index = df["new_var"]

In [70]:
df.index

Int64Index([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
            ...
            244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
           dtype='int64', name='new_var', length=244)